name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: src

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.402
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --framework net6.0 --no-restore --verbosity normal
    - name: Publish net6.0 osx-x64
      run: dotnet publish lyn --framework net6.0 --configuration Release --runtime osx-x64 --self-contained false
    - name: Publish net6.0 linux-x64
      run: dotnet publish lyn --framework net6.0 --configuration Release --runtime linux-x64 --self-contained false
    - name: Publish net6.0 win-x64
      run: dotnet publish lyn --framework net6.0 --configuration Release --runtime win-x64 --self-contained false
    - uses: actions/upload-artifact@v2
      with:
        name: lyn-net6.0-osx-64
        path: src/lyn/bin/Release/net6.0/osx-x64/publish/
    - uses: actions/upload-artifact@v2
      with:
        name: lyn-net6.0-linux-64
        path: src/lyn/bin/Release/net6.0/linux-x64/publish/
    - uses: actions/upload-artifact@v2
      with:
        name: lyn-net6.0-win-64
        path: src/lyn/bin/Release/net6.0/win-x64/publish/
