name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.100-rc.2.22477.23
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --framework net7.0 --no-restore --verbosity normal
    - name: Publish net7.0 osx-x64
      run: dotnet publish lyn --framework net7.0 --configuration Release --runtime osx-x64 --self-contained false
    - name: Publish net7.0 osx-arm64
      run: dotnet publish lyn --framework net7.0 --configuration Release --runtime osx-arm64 --self-contained false
    - name: Publish net7.0 linux-x64
      run: dotnet publish lyn --framework net7.0 --configuration Release --runtime linux-x64 --self-contained false
    - name: Publish net7.0 win-x64
      run: dotnet publish lyn --framework net7.0 --configuration Release --runtime win-x64 --self-contained false
    - uses: actions/upload-artifact@v2
      with:
        name: lyn-net7.0-osx-64
        path: src/lyn/bin/Release/net7.0/osx-x64/publish/
    - uses: actions/upload-artifact@v2
      with:
        name: lyn-net7.0-osx-arm64
        path: src/lyn/bin/Release/net7.0/osx-arm64/publish/
    - uses: actions/upload-artifact@v2
      with:
        name: lyn-net7.0-linux-64
        path: src/lyn/bin/Release/net7.0/linux-x64/publish/
    - uses: actions/upload-artifact@v2
      with:
        name: lyn-net7.0-win-64
        path: src/lyn/bin/Release/net7.0/win-x64/publish/
